package dev.zprestige.mud.util.impl;

import dev.zprestige.mud.util.MC;

public class MudUtil implements MC {

    private static final String[] offTheMudPt2 = new String[]{
            "Like", "grrah",
            "Like, grrah-grrah",
            "Like, drop my 4's, I'm takin' all of yours, you heard?",
            "Sleeze, Ewokk",
            "Drilly, MB-MB",
            "Free Lee, Free Six, you heard?",
            "Free Drilly gang, you heard?",
            "Suck my dick, every opp shot",
            "Like, what?",
            "One false move and I'm makin' it lit",
            "Yeah, for my brothers, I'm takin' that trip",
            "Spin through the S, I'm throwin' more than six",
            "Like, catch Nay Benz, you get flipped like a brick",
            "I'm wit' JB throwin' out the rental",
            "You know that's my brother, for him it get heavy",
            "I'm tired of the dissing and niggas politic",
            "Why this dirty bitch on my dick?",
            "And EK, nigga, stop all the dissin'",
            "Last time I checked, had you runnin', Rick",
            "Bunny hop, Drilly Bop in the spot, wit' the Glock on me",
            "Try to run up, I'ma click",
            "Bunny hop, Drilly Bop in the spot, wit' the Glock on me",
            "Try to run up, I'ma- what?",
            "Bunny hop, Drilly Bop, like, what?",
            "I ain't clickin', why that nigga tripped? I'm on 'em",
            "Chased Rico down the strip",
            "Don't run, don't trip",
            "Accuracy aimin', shootin' like I'm Wick",
            "Don't run, don't trip",
            "Accuracy aimin', I'm shootin' like I'm wick",
            "Don't run, don't trip, don't run, like",
            "Southside, I threw more than ten",
            "Boy lucky he really not dead",
            "Like, spin through the S, i'ma do it again",
            "This time, I see U.E, gon' up to ya' front",
            "Niggas know what I do, what I did",
            "I'm a demon, love shootin' at 'Rips",
            "Too sleeze wit' the pole",
            "James Bond in this bitch",
            "Niggas know we too sturdy wit' it",
            "On the guys, I'm too sturdy wit' it",
            "Like, JB Sleeze really curry wit' it",
            "On the guys, I'm too sturdy wit' it",
            "Like, JB Sleeze really curry wit' it",
            "How many niggas got put in a casket?",
            "He can get shot for sayin', \"What's crackin?\"",
            "Word to my mother, I want all of the static",
            "Lime in the back and he ready to blast it",
            "I'm a devil, it get spooky",
            "Bitch, I'm a devil, yellin' out, \"Whoopty\"",
            "I know a nigga got hit in his goofy",
            "See a opp, beat him out his Ksubis",
            "\"Yo, Eddie, go get 'em\"",
            ".30 clip, aimin' for the neck up",
            "Smokin' on Wheezy, got put on a stretcher",
            "Fuck all the opps, got the knocks in the sweater",
            "Why y'all niggas be mentioning bro?",
            "Huncho a rat, niggas know that you told",
            "I thought you the guys? How the fuck do you fold?",
            "Bitch, I'm a demon, standing ten toes",
            "Off the mud, got me movin' wock",
            "She like, \"Dotty, can I hold your knock?\"",
            "Frankie in the back, tryna clear the spot",
            "Rico got shot, took it on the hop",
            "Free the guys that was takin' that risk",
            "Yoppa, BG, Esco Six",
            "How many dead niggas up in my spliff?",
            "Lola, Nazzy, Poochie, RipK",
            "JB Sleeze throwin' more than six",
            "Bitch, I throw up the Gz 'cause I'm gunnin' for Crips",
            "Fuck all the opps, tell 'em, \"Get off my dick\"",
            "And Jojo a rat, can't beef wit' a snitch",
            "Fuck all the opps, tell 'em, \"Get off my dick\"",
            "I said, \"Jojo a rat, can't beef wit' a-\"",
            "Off the mud, got me movin' wock",
            "She like, \"Dotty, can I hold your knock?\"",
            "Frankie in the back, tryna clear the spot",
            "Rico got shot, took it on the hop",
            "Off the mud, got me movin' wock",
            "She like, \"Dotty, can I hold your knock?\"",
            "Frankie in the back, tryna clear the spot",
            "Rico got shot, took it on the hop",
            "Eddie Gz, niggas know my body",
            "Hop out the car, tryna catch me a body",
            "All my opps, they know where to find me",
            "Catch me on the 4th, totin' on a glocky",
            "And I'm not like [?]",
            "If i catch Nay Benz, she get beat wit' the grip",
            "How ya' team No L'z but your mans in my spliff",
            "Now hold on, i'ma end it like this",
            "Like, how many dead niggas in my spliff?",
            "Like, Diddy, Yellow, C-Hii, Dristy",
            "Dead niggas that got hit",
            "Like, Rippy, Bobby, Nazzy Dristy",
            "Dead Loccs in my spliff",
            "Like, Quado, U.E, Butter, Dristy",
            "Bridge niggas in my spliff",
            "Grrah, grrah, grrah-grrah, double",
            "Mdotty here you heard, drop my 4's, you get sent to the fuckin- (Sleeze)",
            "Nigga, it's Eddie Gz, spin my block, i'm uppin' that Lemon Squeeze",
            "Grra-ta, grra-ta, double Drilly"
    };

    private static final String[] deadOpps = new String[]{
            "NAZZY",
            "RIPPY",
            "BOBBY",
            "DIDDY",
            "NOAH",
            "GRITS",
            "CHARLIE",
            "MEG",
            "ZAY",
            "C-HII",
            "MEZZY",
            "BERRY",
            "MARKY",
            "TANQ",
            "RIPK",
            "GLO",
            "YELLOW",
            "NAZZZYY",
            "QUADO",
            "U.E",
            "BUDDA",
            "BDOT",
            "EDOT",
            "NOTTI",
            "BENJI",
            "COUNTRY",
            "SDOT",
            "JAH LOC",
            "SMELLY",
            "RB",
            "TG",
            "RAH GZ",
            "BLAY",
            "ZOULI",
            "EX",
            "JACOB",
            "THUNDA BLU",
            "MILLY",
            "JAY",
            "REY",
            "JB",
            "CAINE",
            "RICO",
            "EK PAPS",
            "DOUGIE PAPS"
    };


    public static String[] getOffTheMudPt2() {
        return offTheMudPt2;
    }

    public static String[] getDeadOpps() {
        return deadOpps;
    }
}
